source 'https://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'activerecord'
gem 'standalone_migrations'
gem 'ruby-oci8', '~> 2.1.0'
gem 'activerecord-oracle_enhanced-adapter', '~> 1.4.0'
gem 'require_all'


