#
# Info and src for StandaloneMigrations: https://github.com/thuss/standalone-migrations
#
# Creating a new migration
# rake db:new_migration name=foo_bar_migration
# edit db/migrate/20081220234130_foo_bar_migration.rb
#
# Apply latest migration
#
# rake db:migrate
#
# Migrate to a specific version
#
# rake db:migrate VERSION=20131203184957
#
# Migrate a specific database:
#
# rake db:migrate DB=test ... or ...
# rake db:migrate RAILS_ENV=test
#
# Revert last migration
#
# rake db:rollback
#
# Revert last 3 migrations
# rake db:rollback STEP=3
#
require 'rubygems'
require 'rake'
require 'rspec/core/rake_task'
require 'standalone_migrations'

#
# Configure load path for this small project...
# TODO - this is not working for app/models dir, but ok for spec
#
%w{spec app/models}.each do |dir|
  $:.unshift "#{File.dirname(__FILE__)}/#{dir}"
end

RSpec::Core::RakeTask.new(:spec)

task :default  => :spec

StandaloneMigrations::Tasks.load_tasks



